events { 
    worker_connections 1024; 
}

http {
    # 'app' is the name of the service in docker-compose.yml
    # Docker's internal DNS automatically routes this to all 3 replicas!
    upstream node_cluster {
        least_conn; # Load balancing method: least connections
        server app:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://node_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}